### ISSUE TITLE
Private fields naming convention decision

### ISSUE THREAD

**Issue by duracellko** [ERNICommunity/csharp-coding-conventions#1]
There are 2 suggestions for naming convention of private fields. We have to decide, which approach to follow.

### camelCase

Private field should begin with lower case. This apply for static fields as well. Private fields should not start with underscore or any other prefix.

To distinguish between local and member variables use `this.`

### camelCase with underscore prefix

Private field should begin with underscore followed by lower case. This apply for static fields as well.

This way fields are distinguished from local variables and parameters. `this` keyword should not be used, unless necessary.

**Comment by hitclif** [comment]
I prefer the underscore `_myVar`. The readability of the code using the underscore (without this.) is better.

```
class Foo 
{
    private int myVariable;

    public int MyVariable {
        get { return this.MyVariable }
        set { this.myVariable = value; }
    }
}
```

vs.

```
class Foo 
{
    private int _myVariable;

    public int MyVariable {
        get { return _myVariable }
        set { _myVariable = value; }
    }
}
```

Note: the getter contains a bug get { return this.MyVariable } (returns property instead of instance, causing recursive call which end with Exception)

**Comment by laco-gunis** [comment]
Resolved: camelCase with underscore prefix
