### ISSUE TITLE
tab vs spaces

### ISSUE THREAD

**Issue by duracellko** [ERNICommunity/csharp-coding-conventions#3]
We have to decide whether to use tabs or spaces for indentation.

### Tabs

Use tabs for indentation. Do not use spaces. Recommended tab size is 4, but always format code in a way that is compatible with arbitrary tab size.

### Spaces

Use spaces for indentation. Do not use tabs. Lines are indented by 4 spaces.

**Comment by hitclif** [comment]
I suggest `spaces`. Resharper: "Use spaces (recommended, looks aligned on any tab size)"

**Comment by DiegoBao** [comment]
I would suggest spaces as well. All editors today manage the space/tab conversions very well.

**Comment by laco-gunis** [comment]
Resolved: space intendation
