### ISSUE TITLE
Using using inside or outside namespace

### ISSUE THREAD

**Issue by jakub-sturc** [ERNICommunity/csharp-coding-conventions#7]
Should we use this:

```csharp
namespace ERNI.Sample
{
    using System;
    public class SampleClass
    { 
        // ....
    }
}
```
or this
```csharp
using System;
namespace ERNI.Sample
{
    public class SampleClass
    { 
        // ....
    }
}
```
Please not there is [subtle difference](http://stackoverflow.com/a/151560/2361) between those usages.

**Comment by DiegoBao** [comment]
I understand the diference in the uses. But to tell you the truth in all my years of programming in .net (that's basically since .net was released) I have never ever run in the need to use the inner syntax. So I would go for the second option in this one.

**Comment by cajo-ph** [comment]
I would also go for the "outer" approach since this is the default when Visual Studio automatically adds referenced namespace. If we follow the inner approach, we have to manually do the movement for newly-added namespaces.

**Comment by laco-gunis** [comment]
Resolved:  outer using syntax
